import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import { defineConfig, globalIgnores } from 'eslint/config'
import tseslint from 'typescript-eslint'

/**
 * ESLint flat config (F055). Name and shape follow the reference project's
 * `eslint.config.mjs`, retargeted from Next.js to this Vite SPA — there is no
 * `eslint-config-next` here, so `@eslint/js` supplies the core recommended set
 * and `typescript-eslint` supplies the TypeScript rules
 * (`docs/REFERENCE_PARITY.md`).
 *
 * **Not type-aware, on purpose.** `recommendedTypeChecked` would duplicate what
 * `tsc --noEmit` already does across the whole tree (`pnpm run typecheck`, run
 * by `pnpm run build`), at the cost of a type-checked lint pass that is slow
 * enough to discourage running it. Types are checked by the compiler; this
 * config checks the things the compiler does not — unused code, hook rules,
 * accidental `any`, and the Fast Refresh boundary.
 */
export default defineConfig([
  globalIgnores([
    // Build output and reports.
    'dist/',
    'coverage/',
    // Generated by `pnpm run api:types` (F018): the generator owns these bytes,
    // CI (F061) regenerates them and fails on any diff. Never lint them.
    'src/lib/generated/',
    // Normalised by `scripts/fix-generated-ui.sh` after every `shadcn add`;
    // the registry owns their shape (F014, ARCHITECTURE §5).
    'src/components/ui/',
  ]),
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // `configs.flat.*` is the flat-config half of this plugin: the unprefixed
  // `configs.recommended*` entries are still eslintrc-shaped (a string array
  // under `plugins`), which flat config rejects at load time.
  reactHooks.configs.flat['recommended-latest'],
  reactRefresh.configs.vite,
  {
    files: ['**/*.{ts,tsx}'],
    rules: {
      // TypeScript already rejects unused locals and parameters
      // (`noUnusedLocals`/`noUnusedParameters` in tsconfig.json), so the
      // underscore prefix is the only escape hatch left: it marks a parameter
      // that must be declared for the signature but is deliberately unused.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Two rules in the sets above are switched off deliberately, each for the
    // reason recorded in DECISIONS C43 — this is a disclosed choice, not a
    // silence:
    //
    // - `react-refresh/only-export-components` is a Fast Refresh granularity
    //   rule. The provider modules here export the provider *and* its hook
    //   (`AuthProvider`/`useAuth`, `ThemeProvider`/`useTheme`, …), which is the
    //   documented pattern (ARCHITECTURE §5); editing one costs a full dev
    //   reload, and splitting the pair to buy that back is not worth it.
    // - `react-hooks/set-state-in-effect` encodes a React Compiler constraint,
    //   and this SPA does not enable the compiler. Seeding editable state from
    //   a fetched snapshot exactly once is the behaviour the admin pages need —
    //   `roles.tsx` spells out why a background refetch must not clobber edits.
    //   `rules-of-hooks` and `exhaustive-deps`, the two rules that catch real
    //   bugs, stay on.
    rules: {
      'react-refresh/only-export-components': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  {
    // Tests use Vitest's globals (`globals: true` in vite.config.ts), and the
    // generated client is a plain data module. `no-undef` is off for TS files
    // through `typescript-eslint`, so nothing here needs a globals block — but
    // tests get one relaxed rule: assertions on `document` bodies read better
    // with a non-null assertion whose absence the compiler cannot prove.
    files: ['tests/**/*.{ts,tsx}'],
    rules: {},
  },
])
