"""The reports this application produces from authorized rows (F053, BP-7.9c).

``app/services/reports.py`` renders a document it is handed; this module decides
*what* the document says, and it is the only place a report reads the database.
The split is the point: the engine holds no opinion about who may see what, and
this module holds no opinion about page furniture.

Two rules, and both are load-bearing:

- **A report draws the rows its caller may read, and no others.** The directory
  report asks ``users.directory_criteria`` for its WHERE clause — the same
  function the paged directory endpoint uses (F033) — so the export is, by
  construction, exactly the subset of accounts the caller could already list.
  The endpoint adds the permission gate (``reports.generate`` beside
  ``users.read``); this module never widens what the caller can reach.
- **A report is bounded.** One document is built in memory, so the row count is
  capped (:data:`MAX_DIRECTORY_ROWS`) and exceeding it is a *refusal* that names
  the limit rather than a document that quietly stops (see :class:`TooManyRows`).
  A directory can outgrow a single export; a report that lies about being
  complete cannot be un-lied.

The words are the caller's (C29 is still open, so nothing here brands anything),
and every value that reaches the engine goes through its escaping — the renderer
escapes markup, and this module passes raw text to it.
"""

from datetime import UTC, datetime
from typing import Final

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.identity import User
from app.services import users as users_service
from app.services.reports import ReportDocument, ReportSection, ReportTable

# How many accounts one export may carry. Not a product rule — a bound on what
# this process will hold while it renders (reportlab builds the whole flowable
# list before it starts a page) and a number a reader can be told. Raised when a
# deployment's directory outgrows it, with the reason recorded then.
MAX_DIRECTORY_ROWS: Final = 1000

# The directory screen's columns, in its order. A report that showed a different
# set would make "what you see" and "what you get" two different claims.
COLUMNS: Final = ("Full name", "Email", "Roles", "Status", "Created")


class TooManyRows(Exception):
    """The report is larger than this service will build in one document."""


async def user_directory_document(
    session: AsyncSession,
    *,
    search: str | None,
    is_active: bool | None,
    sort: str,
    order: str,
    generated_by: str,
    generated_at: datetime,
    limit: int | None = None,
) -> ReportDocument:
    """The user directory as a report, filtered exactly as the caller asked.

    ``generated_by`` is the caller's name, which travels into the PDF's author
    metadata — a file that leaves this service says who produced it. Both it and
    ``generated_at`` are supplied rather than read here: the route already knows
    the session, and one instant serves the document, its footer and the
    filename the caller receives.

    ``limit`` defaults to :data:`MAX_DIRECTORY_ROWS` **read at call time**, not
    bound as a default argument: a test proves the refusal by lowering the
    ceiling, and a thousand accounts is not how that should be tested.
    """
    limit = MAX_DIRECTORY_ROWS if limit is None else limit
    # One row past the cap, so "at the limit" and "over it" are different
    # answers without a second count query.
    rows = await users_service.directory_rows(
        session,
        search=search,
        is_active=is_active,
        sort=sort,
        order=order,
        limit=limit + 1,
    )
    if len(rows) > limit:
        raise TooManyRows(
            f"This export would contain more than {limit} accounts. Narrow the "
            f"filters: one report covers up to {limit} rows.",
        )

    return ReportDocument(
        title="User Directory",
        subtitle=_scope(search, is_active),
        metadata=(
            ("Accounts", str(len(rows))),
            ("Generated by", generated_by),
            # Cells carry calendar dates; a reader has to know the zone they
            # were taken in, or a date near midnight is a day out for anybody
            # east of UTC (display conversion is the UI's job — C29/F048).
            ("Time zone", "UTC"),
        ),
        sections=_empty_notice(rows),
        tables=(
            ReportTable(
                columns=COLUMNS,
                rows=[_row(user) for user in rows],
                heading="Accounts",
            ),
        ),
        subject="User Directory",
        author=generated_by,
        generated_at=generated_at,
    )


def _scope(search: str | None, is_active: bool | None) -> str:
    """The filters, said the way the screen's controls read."""
    parts: list[str] = []
    if is_active is not None:
        parts.append("Active accounts" if is_active else "Inactive accounts")
    else:
        parts.append("Every account")
    if search:
        # ASCII quotes: the built-in fonts are the Latin-1 set (C39), and
        # typographic quotes are outside it.
        parts.append(f'matching "{search.strip()}"')
    return " · ".join(parts)


def _empty_notice(rows: list[User]) -> tuple[ReportSection, ...]:
    """A sentence where the table would be, when nothing matched.

    A header row on its own is the same picture as a table whose rows failed to
    print. The words say which of the two happened.
    """
    if rows:
        return ()
    return (ReportSection("Accounts", ("No account matches these filters.",)),)


def _row(user: User) -> tuple[str, ...]:
    """One account as cells — the same values the directory screen shows."""
    roles = ", ".join(sorted(role.name for role in user.roles))
    return (
        user.full_name,
        user.email,
        roles or "None",
        "Active" if user.is_active else "Inactive",
        user.created_at.astimezone(UTC).strftime("%Y-%m-%d"),
    )
