import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * The credentials a browser run shares between its own steps (F057).
 *
 * Two writers, one file:
 *
 * - `backend/scripts/e2e_database.py` writes the super-admin's address and the
 *   freshly generated password before the API starts, and
 * - step 2 of the workflow rewrites the password, because the account is
 *   forced to change it on first sign-in — which is exactly what BP-10.4 asks
 *   the browser to prove.
 *
 * The file lives under `.state/`, which is git-ignored: it holds a per-run
 * credential for an isolated database, and nothing outside the run reads it.
 * It is **not** the place for anything durable — every `playwright test`
 * invocation starts by recreating the database and overwriting this file.
 */
const here = path.dirname(fileURLToPath(import.meta.url))

export const STATE_FILE = path.resolve(here, '..', '.state', 'state.json')

export interface E2EState {
  /** The bootstrapped super-admin, as `e2e_database.py` created it. */
  adminEmail: string
  /** Its current password: generated by the preparation, then changed by step 2. */
  adminPassword: string
  databaseName: string
  preparedAt: string
}

export function readState(): E2EState {
  return JSON.parse(fs.readFileSync(STATE_FILE, 'utf8')) as E2EState
}

export function updateState(changes: Partial<E2EState>): E2EState {
  const next = { ...readState(), ...changes }
  fs.writeFileSync(STATE_FILE, `${JSON.stringify(next, null, 2)}\n`, 'utf8')
  return next
}

/**
 * Accounts the workflow creates through the UI, kept for the steps that need
 * them after the page that made them is gone.
 *
 * Module-level rather than in the file above because these are *within* one
 * run: the API server holds the accounts, so a value written here and a value
 * in the database can never disagree. The single worker (`playwright.config.ts`
 * explains why) is what makes a module-level record safe.
 */
export interface RunAccounts {
  /** Step 3: the ordinary account, with two roles. */
  memberEmail?: string
  memberPassword?: string
  /** Step 8: the second account, whose inbox must stay separate. */
  secondEmail?: string
  secondPassword?: string
}

export const run: RunAccounts = {}

/**
 * A password that satisfies the policy for a generated account.
 *
 * The policy is length ≥ 12 plus a denylist (F026); a fixed prefix with a
 * random tail keeps these readable in a failure message while still being
 * different every run — the requirement's "generated test credentials".
 */
export function generatedPassword(): string {
  return `E2e-${Math.random().toString(36).slice(2, 10)}-${Date.now().toString(36)}`
}

/**
 * Emails are unique per run, so a leftover row can never collide with them.
 *
 * The domain is an ordinary one, not `.test`/`.invalid`: the API's email
 * validation refuses reserved testing TLDs, and a 422 on the create form is a
 * confusing way to learn that. Nothing ever sends mail to it.
 */
const EMAIL_DOMAIN = 'resors-e2e.com'

export function runEmail(name: string): string {
  return `${name}-${Math.random().toString(36).slice(2, 8)}@${EMAIL_DOMAIN}`
}
