"""sessions table

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09

Autogenerated from the models (``alembic revision --autogenerate``) and
reviewed: the shape below is exactly what ``app/models/session.py`` declares.
Applies to an empty database and comes back down again (ARCHITECTURE §9).

What the constraints are doing, so a later migration does not weaken them by
accident:

- ``ck_sessions_token_hash_is_sha256_hex`` — the column holds the SHA-256 hex
  digest of the cookie's value and nothing else. The same pattern is exported
  as ``SESSION_TOKEN_HASH_PATTERN`` in ``app/core/security.py``, so raw tokens
  are impossible to store, from any path, including a psql session.
- ``ck_sessions_idle_deadline_within_absolute`` — the two deadlines are
  ordered; idle is the one activity moves, absolute is the one it cannot.
- ``ck_sessions_revocation_is_complete`` / ``ck_sessions_revoked_reason_is_known``
  — a revocation always says why, over a closed vocabulary F029's replay
  detection and the audit trail match on.
- ``ix_sessions_token_hash`` (unique) — the per-request lookup key.
- ``ix_sessions_replaced_by_id`` (unique) — rotation chains are walkable, and
  a session is the successor of at most one predecessor.
- ``fk_sessions_user_id_users`` ON DELETE CASCADE — deleting a user (F033's
  hard delete would be rare; the cascade exists so it *cannot* be unsafe)
  takes their sessions with them. ``fk_sessions_replaced_by_id_sessions``
  ON DELETE SET NULL — pruning an expired successor leaves the predecessor's
  revocation record intact.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=32), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "revoked_reason IN ('logout', 'logout_all', 'rotated', 'theft_detected', "
            "'password_change', 'admin')",
            name=op.f("ck_sessions_revoked_reason_is_known"),
        ),
        sa.CheckConstraint(
            "token_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_sessions_token_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "(revoked_at IS NULL) = (revoked_reason IS NULL)",
            name=op.f("ck_sessions_revocation_is_complete"),
        ),
        sa.CheckConstraint(
            "idle_expires_at <= absolute_expires_at",
            name=op.f("ck_sessions_idle_deadline_within_absolute"),
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["sessions.id"],
            name=op.f("fk_sessions_replaced_by_id_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_family_id"), "sessions", ["family_id"], unique=False)
    op.create_index(op.f("ix_sessions_replaced_by_id"), "sessions", ["replaced_by_id"], unique=True)
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_replaced_by_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_family_id"), table_name="sessions")
    op.drop_table("sessions")
