"""rate_limit_buckets

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-10

Autogenerated from the models (``alembic revision --autogenerate``) and
reviewed: the shape below is exactly what ``app/models/rate_limit.py``
declares. Applies to an empty database and comes back down again
(ARCHITECTURE §9).

One row per throttle key, holding a fixed window and the hits counted in it —
the DB-backed answer to "no Redis" (ARCHITECTURE §8). What matters:

- ``ix_rate_limit_buckets_bucket_key`` (unique) is both the lookup index and
  the ``ON CONFLICT`` target of the atomic upsert in ``app/core/rate_limit.py``
  — the statement that makes concurrent logins count correctly without a lock.
- ``ck_rate_limit_buckets_hit_count_is_positive`` — a bucket exists because
  something was counted; zero is not a state the table represents.
- ``bucket_key`` is 400 wide because the longest key its helpers build is
  ``login:account:`` plus a 320-character email, and a key that would be
  silently truncated would split one throttle budget into two.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "rate_limit_buckets",
        sa.Column("bucket_key", sa.String(length=400), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hit_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "hit_count >= 1",
            name=op.f("ck_rate_limit_buckets_hit_count_is_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit_buckets")),
    )
    op.create_index(
        op.f("ix_rate_limit_buckets_bucket_key"),
        "rate_limit_buckets",
        ["bucket_key"],
        unique=True,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_rate_limit_buckets_bucket_key"), table_name="rate_limit_buckets")
    op.drop_table("rate_limit_buckets")
