"""audit log

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-10 03:43:58.944147

Every migration must apply to an **empty** database and come back down again
(ARCHITECTURE §9): "downgrade where feasible; no drift on repeat".
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_email", sa.String(length=320), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "action IN ('user.create', 'user.update', 'user.delete', 'user.reset_password', 'profile.update', 'preference.set', 'preference.delete', 'role.create', 'role.update', 'role.delete', 'role.matrix_save', 'permission.create', 'permission.update', 'permission.delete', 'setting.update')",
            name=op.f("ck_audit_logs_action_is_known"),
        ),
        sa.CheckConstraint(
            "entity_type IN ('user', 'profile', 'preference', 'role', 'permission', 'setting')",
            name=op.f("ck_audit_logs_entity_type_is_known"),
        ),
        sa.CheckConstraint(
            "length(trim(summary)) > 0", name=op.f("ck_audit_logs_summary_is_present")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
