"""notifications

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-10 04:05:01.369529

Every migration must apply to an **empty** database and come back down again
(ARCHITECTURE §9): "downgrade where feasible; no drift on repeat".
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "link IS NULL OR link ~ '^/[A-Za-z0-9]'",
            name=op.f("ck_notifications_link_is_an_internal_path"),
        ),
        sa.CheckConstraint(
            "length(trim(message)) > 0", name=op.f("ck_notifications_message_is_present")
        ),
        sa.CheckConstraint(
            "length(trim(title)) > 0", name=op.f("ck_notifications_title_is_present")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_user_id_created_at"),
        "notifications",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_user_id_created_at"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
