"""file assets

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-10 13:40:00.000000

Every migration must apply to an **empty** database and come back down again
(ARCHITECTURE §9): "downgrade where feasible; no drift on repeat".

Two things happen here. The table is ordinary autogenerated work; the audit
constraints below are **hand-written**, because Alembic cannot see a CHECK
whose expression changed — the model's vocabulary grew (F049 adds
``file.create``/``file.delete`` and the ``file`` entity type) and only a real
``ALTER`` teaches the database about it. The expressions are the model's,
spelled out as literals: a migration must not import the code it is migrating
past.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The vocabularies as `app/models/audit.py` spells them *after* F049, and as it
# spelled them before. Kept as literals on purpose (see the module docstring):
# a migration must not import the code it is migrating past, and the downgrade
# has to restore the older string exactly.
ACTION_IS_KNOWN = (
    "action IN ('user.create', 'user.update', 'user.delete', 'user.reset_password', "
    "'profile.update', 'preference.set', 'preference.delete', 'role.create', "
    "'role.update', 'role.delete', 'role.matrix_save', 'permission.create', "
    "'permission.update', 'permission.delete', 'setting.update', "
    "'file.create', 'file.delete')"
)
ENTITY_TYPE_IS_KNOWN = (
    "entity_type IN ('user', 'profile', 'preference', 'role', 'permission', "
    "'setting', 'file')"
)

# Revision 0007's expressions, restored verbatim on the way down.
ACTION_IS_KNOWN_0007 = (
    "action IN ('user.create', 'user.update', 'user.delete', 'user.reset_password', "
    "'profile.update', 'preference.set', 'preference.delete', 'role.create', "
    "'role.update', 'role.delete', 'role.matrix_save', 'permission.create', "
    "'permission.update', 'permission.delete', 'setting.update')"
)
ENTITY_TYPE_IS_KNOWN_0007 = (
    "entity_type IN ('user', 'profile', 'preference', 'role', 'permission', 'setting')"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_assets",
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=36), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category ~ '^[a-z][a-z0-9_.-]*$'",
            name=op.f("ck_file_assets_category_is_well_formed"),
        ),
        sa.CheckConstraint(
            "length(trim(content_type)) > 0",
            name=op.f("ck_file_assets_content_type_is_present"),
        ),
        sa.CheckConstraint(
            "key ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'",
            name=op.f("ck_file_assets_key_is_an_object_name"),
        ),
        sa.CheckConstraint(
            "length(trim(original_filename)) > 0",
            name=op.f("ck_file_assets_original_filename_is_present"),
        ),
        sa.CheckConstraint(
            "sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_file_assets_sha256_is_a_digest")
        ),
        sa.CheckConstraint("size > 0", name=op.f("ck_file_assets_size_is_positive")),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_file_assets_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_assets")),
    )
    op.create_index(op.f("ix_file_assets_key"), "file_assets", ["key"], unique=True)
    op.create_index(
        op.f("ix_file_assets_owner_user_id_created_at"),
        "file_assets",
        ["owner_user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Hand-written: the audit vocabularies gained the file events (F049). The
    # constraints are dropped and recreated rather than renamed, so the model's
    # spelling and the database's stay the same string.
    op.drop_constraint(op.f("ck_audit_logs_action_is_known"), "audit_logs", type_="check")
    op.drop_constraint(op.f("ck_audit_logs_entity_type_is_known"), "audit_logs", type_="check")
    op.create_check_constraint(
        op.f("ck_audit_logs_action_is_known"), "audit_logs", ACTION_IS_KNOWN
    )
    op.create_check_constraint(
        op.f("ck_audit_logs_entity_type_is_known"), "audit_logs", ENTITY_TYPE_IS_KNOWN
    )


def downgrade() -> None:
    # Narrowing the vocabulary back is a plain ALTER, and it **fails loudly**
    # if any row still uses a file action — which is the honest outcome:
    # dropping the table below does not remove those rows, and a silent
    # rewrite of the trail would be worse than a refusal.
    op.drop_constraint(op.f("ck_audit_logs_action_is_known"), "audit_logs", type_="check")
    op.drop_constraint(op.f("ck_audit_logs_entity_type_is_known"), "audit_logs", type_="check")
    op.create_check_constraint(
        op.f("ck_audit_logs_action_is_known"),
        "audit_logs",
        ACTION_IS_KNOWN_0007,
    )
    op.create_check_constraint(
        op.f("ck_audit_logs_entity_type_is_known"),
        "audit_logs",
        ENTITY_TYPE_IS_KNOWN_0007,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_assets_owner_user_id_created_at"), table_name="file_assets")
    op.drop_index(op.f("ix_file_assets_key"), table_name="file_assets")
    op.drop_table("file_assets")
    # ### end Alembic commands ###
