"""disciplines

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-10 22:39:53.691498

The first domain revision (DOMAIN_ARCHITECTURE §1: the map reserves no
numbers, and the first task to add a table takes `0010`).

Creates one table, `disciplines`, exactly as `app/models/masters.py` declares
it: UUID v7 primary key from the database, `timestamptz` instants, a unique
index on `code`, and the two CHECKs the model carries. Ordinary autogenerated
work — no hand-written clause, because nothing in the foundation's existing
tables changes with it.

**No rows are inserted here, deliberately.** The seven initial values are the
seed's (`app/seed.py`, D002's own acceptance: idempotent seed tests), and a
data-insert in a migration would be a second source of truth for which values
exist — one that cannot be re-run, cannot report what it did, and would race
the seed on a database that runs both. `alembic upgrade head` leaves the table
empty; `python -m app.seed` fills it, and `app/bootstrap_admin.py` calls the
same function inside its own transaction.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disciplines",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code ~ '^[a-z][a-z0-9_]*$'",
            name=op.f("ck_disciplines_code_is_well_formed"),
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0",
            name=op.f("ck_disciplines_name_is_present"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disciplines")),
    )
    op.create_index(op.f("ix_disciplines_code"), "disciplines", ["code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_disciplines_code"), table_name="disciplines")
    op.drop_table("disciplines")
    # ### end Alembic commands ###
