"""departments

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-10 22:48:57.520917

The second domain revision (D003; DOMAIN_ARCHITECTURE §2's `departments` row,
`code UQ, name, classification HEAD_OFFICE|SITE, is_active`). The number is
read from the directory, never from a plan (D001 §5).

Creates one table, `departments`, exactly as `app/models/masters.py` declares
it: UUID v7 primary key from the database, `timestamptz` instants, a unique
index on `code`, and the three CHECKs the model carries — the two `disciplines`
also has, plus the closed classification vocabulary. Ordinary autogenerated
work — no hand-written clause, because nothing in an existing table changes
with it.

**No rows are inserted here, deliberately — and none anywhere else either.**
The specification names no initial departments (unlike the seven disciplines,
`PRODUCT_SPEC` §3 stops at the columns), so `alembic upgrade head` leaves this
table empty and that is its finished state: an operator defines their own head
office and sites. `app/seed.py` writes nothing here, which is why a seed run is
still a no-op over a migrated database.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code ~ '^[a-z][a-z0-9_]*$'",
            name=op.f("ck_departments_code_is_well_formed"),
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0",
            name=op.f("ck_departments_name_is_present"),
        ),
        sa.CheckConstraint(
            "classification IN ('HEAD_OFFICE', 'SITE')",
            name=op.f("ck_departments_classification_is_known"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
    )
    op.create_index(op.f("ix_departments_code"), "departments", ["code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_departments_code"), table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
