"""designations

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-10 22:57:46.020424

The third domain revision (D004; DOMAIN_ARCHITECTURE §2's `designations` row,
`code UQ, name, department_id → departments, discipline_id → disciplines,
is_active`). The number is read from the directory, never from a plan (D001 §5).

Creates one table, `designations`, exactly as `app/models/masters.py` declares
it: UUID v7 primary key from the database, `timestamptz` instants, a unique
index on `code`, the two CHECKs `disciplines` and `departments` also carry, and
**two `NOT NULL` foreign keys** — the first in this tree — each with its own
index. `ON DELETE RESTRICT` is deliberate: a department or a discipline that a
designation still names cannot be deleted, which is the schema's half of the
product's "deactivate, never delete where a row is referenced" policy
(DOMAIN_ARCHITECTURE §3). Ordinary autogenerated work, reviewed: the diff was
the new table and the three indexes and nothing else.

**No rows are inserted here, deliberately — and none anywhere else either.**
The specification names no initial designations (`PRODUCT_SPEC` §3 stops at the
columns), so `alembic upgrade head` leaves this table empty and that is its
finished state. `app/seed.py` writes nothing here, so a seed run stays a no-op
over a migrated database.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "designations",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("discipline_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code ~ '^[a-z][a-z0-9_]*$'",
            name=op.f("ck_designations_code_is_well_formed"),
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0",
            name=op.f("ck_designations_name_is_present"),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_designations_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["discipline_id"],
            ["disciplines.id"],
            name=op.f("fk_designations_discipline_id_disciplines"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_designations")),
    )
    op.create_index(op.f("ix_designations_code"), "designations", ["code"], unique=True)
    op.create_index(
        op.f("ix_designations_department_id"), "designations", ["department_id"], unique=False
    )
    op.create_index(
        op.f("ix_designations_discipline_id"), "designations", ["discipline_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_designations_discipline_id"), table_name="designations")
    op.drop_index(op.f("ix_designations_department_id"), table_name="designations")
    op.drop_index(op.f("ix_designations_code"), table_name="designations")
    op.drop_table("designations")
    # ### end Alembic commands ###
