"""audit master vocabulary

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-10 23:40:00.000000

The master-data revision (D005). It creates no table: the schema it belongs to
is `audit_logs`, and the change is the **closed vocabulary** that table's two
CHECK constraints hold — the nine `discipline|department|designation.*` actions
and the three `discipline|department|designation` entity types the new CRUD
surface records (DOMAIN_ARCHITECTURE §3, `app/models/audit.py`).

Hand-written, like 0009's half, and for the same reason: Alembic cannot see a
CHECK whose *expression* changed, so a widened vocabulary reaches the database
only through a real `ALTER`. The expressions are spelled out as literals — a
migration must not import the code it is migrating past — and the downgrade
restores 0009's pair verbatim.

There is one dialect rule worth knowing before this runs: widening a CHECK is
a validation pass over the existing rows, so this `upgrade` succeeds on any
table whose rows all satisfy the *old* expressions (every row written by an
earlier revision does — they were checked on the way in). The `downgrade`
narrows again and therefore **fails loudly** if a master-data event has since
been written; that is the honest outcome, and the same one 0009 records.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The vocabularies as `app/models/audit.py` spells them *after* D005, and as it
# spelled them before (0009's pair, which F049 widened from 0007's). Literals
# on purpose: see the module docstring.
ACTION_IS_KNOWN = (
    "action IN ('user.create', 'user.update', 'user.delete', 'user.reset_password', "
    "'profile.update', 'preference.set', 'preference.delete', 'role.create', "
    "'role.update', 'role.delete', 'role.matrix_save', 'permission.create', "
    "'permission.update', 'permission.delete', 'setting.update', "
    "'file.create', 'file.delete', "
    "'discipline.create', 'discipline.update', 'discipline.delete', "
    "'department.create', 'department.update', 'department.delete', "
    "'designation.create', 'designation.update', 'designation.delete')"
)
ENTITY_TYPE_IS_KNOWN = (
    "entity_type IN ('user', 'profile', 'preference', 'role', 'permission', "
    "'setting', 'file', 'discipline', 'department', 'designation')"
)

# Revision 0009's expressions, restored verbatim on the way down.
ACTION_IS_KNOWN_0009 = (
    "action IN ('user.create', 'user.update', 'user.delete', 'user.reset_password', "
    "'profile.update', 'preference.set', 'preference.delete', 'role.create', "
    "'role.update', 'role.delete', 'role.matrix_save', 'permission.create', "
    "'permission.update', 'permission.delete', 'setting.update', "
    "'file.create', 'file.delete')"
)
ENTITY_TYPE_IS_KNOWN_0009 = (
    "entity_type IN ('user', 'profile', 'preference', 'role', 'permission', 'setting', 'file')"
)


def upgrade() -> None:
    # No `### commands auto generated by Alembic ###` block: this revision
    # changes nothing Alembic's autogenerate can see, which is the whole
    # reason it is written by hand.
    op.drop_constraint(op.f("ck_audit_logs_action_is_known"), "audit_logs", type_="check")
    op.drop_constraint(op.f("ck_audit_logs_entity_type_is_known"), "audit_logs", type_="check")
    op.create_check_constraint(op.f("ck_audit_logs_action_is_known"), "audit_logs", ACTION_IS_KNOWN)
    op.create_check_constraint(
        op.f("ck_audit_logs_entity_type_is_known"), "audit_logs", ENTITY_TYPE_IS_KNOWN
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_audit_logs_action_is_known"), "audit_logs", type_="check")
    op.drop_constraint(op.f("ck_audit_logs_entity_type_is_known"), "audit_logs", type_="check")
    op.create_check_constraint(
        op.f("ck_audit_logs_action_is_known"), "audit_logs", ACTION_IS_KNOWN_0009
    )
    op.create_check_constraint(
        op.f("ck_audit_logs_entity_type_is_known"), "audit_logs", ENTITY_TYPE_IS_KNOWN_0009
    )
