"""projects audit vocabulary

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-10 23:59:00.000000

The projects revision (D008, the API half). It creates no table — D007's
`0014` did that — and the change is the **closed vocabulary** `audit_logs`'
two CHECK constraints hold: the three `project.*` actions and the `project`
entity type the new CRUD surface records (DOMAIN_ARCHITECTURE §3,
`app/models/audit.py`).

Hand-written, like 0009's and 0013's halves, and for the same reason: Alembic
cannot see a CHECK whose *expression* changed, so a widened vocabulary reaches
the database only through a real `ALTER`. The expressions are literals — a
migration must not import the code it is migrating past — and the downgrade
restores 0013's pair verbatim.

Widening a CHECK is a validation pass over the existing rows, so this
`upgrade` succeeds on any table whose rows all satisfy the *old* expressions
(every row written by an earlier revision does — they were checked on the way
in). The `downgrade` narrows again and therefore **fails loudly** if a project
event has been written since; that is the honest outcome, and the one 0009 and
0013 record.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The vocabularies as `app/models/audit.py` spells them *after* D008.
ACTION_IS_KNOWN = (
    "action IN ('user.create', 'user.update', 'user.delete', 'user.reset_password', "
    "'profile.update', 'preference.set', 'preference.delete', 'role.create', "
    "'role.update', 'role.delete', 'role.matrix_save', 'permission.create', "
    "'permission.update', 'permission.delete', 'setting.update', "
    "'file.create', 'file.delete', "
    "'discipline.create', 'discipline.update', 'discipline.delete', "
    "'department.create', 'department.update', 'department.delete', "
    "'designation.create', 'designation.update', 'designation.delete', "
    "'project.create', 'project.update', 'project.delete')"
)
ENTITY_TYPE_IS_KNOWN = (
    "entity_type IN ('user', 'profile', 'preference', 'role', 'permission', "
    "'setting', 'file', 'discipline', 'department', 'designation', 'project')"
)

# Revision 0013's expressions, restored verbatim on the way down — spelled out
# rather than derived from the pair above by string surgery, because a
# derivation would silently follow a later edit to this file and a migration
# is frozen the moment it is applied.
ACTION_IS_KNOWN_0013 = (
    "action IN ('user.create', 'user.update', 'user.delete', 'user.reset_password', "
    "'profile.update', 'preference.set', 'preference.delete', 'role.create', "
    "'role.update', 'role.delete', 'role.matrix_save', 'permission.create', "
    "'permission.update', 'permission.delete', 'setting.update', "
    "'file.create', 'file.delete', "
    "'discipline.create', 'discipline.update', 'discipline.delete', "
    "'department.create', 'department.update', 'department.delete', "
    "'designation.create', 'designation.update', 'designation.delete')"
)
ENTITY_TYPE_IS_KNOWN_0013 = (
    "entity_type IN ('user', 'profile', 'preference', 'role', 'permission', "
    "'setting', 'file', 'discipline', 'department', 'designation')"
)


def upgrade() -> None:
    # No `### commands auto generated by Alembic ###` block: this revision
    # changes nothing Alembic's autogenerate can see, which is the whole
    # reason it is written by hand.
    op.drop_constraint(op.f("ck_audit_logs_action_is_known"), "audit_logs", type_="check")
    op.drop_constraint(op.f("ck_audit_logs_entity_type_is_known"), "audit_logs", type_="check")
    op.create_check_constraint(op.f("ck_audit_logs_action_is_known"), "audit_logs", ACTION_IS_KNOWN)
    op.create_check_constraint(
        op.f("ck_audit_logs_entity_type_is_known"), "audit_logs", ENTITY_TYPE_IS_KNOWN
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_audit_logs_action_is_known"), "audit_logs", type_="check")
    op.drop_constraint(op.f("ck_audit_logs_entity_type_is_known"), "audit_logs", type_="check")
    op.create_check_constraint(
        op.f("ck_audit_logs_action_is_known"), "audit_logs", ACTION_IS_KNOWN_0013
    )
    op.create_check_constraint(
        op.f("ck_audit_logs_entity_type_is_known"), "audit_logs", ENTITY_TYPE_IS_KNOWN_0013
    )
