"""Engine, sessions and the schema conventions every table follows.

F023 establishes three things that outlive the task, because changing them
later means rewriting migrations:

- **Explicit constraint names.** ``Base.metadata`` carries a naming convention,
  so an unnamed ``UniqueConstraint`` still reaches PostgreSQL as
  ``uq_<table>_<columns>``. Without one, constraint names are generated by the
  database, differ between environments, and every ``ALTER``/``DROP`` in a
  migration becomes guesswork.
- **UUID primary keys, version 7, generated by PostgreSQL.** ``uuidv7()`` is
  time-ordered, so new rows land at the end of the primary-key index instead of
  scattering through it the way v4 does — the same index locality as a
  sequence, without giving up an ID that is safe to expose. It requires
  PostgreSQL 18; this project pins 18.6 (ARCHITECTURE §8).
- **``timestamptz`` instants, never naive timestamps.** ``created_at`` and
  ``updated_at`` are UTC instants stored with a timezone; display-time
  conversion is a frontend concern (§14: "UTC instants for events").

The engine is created lazily. Importing this module must never require a
database — ``scripts/export_openapi.py`` imports the app to emit the schema,
and that has to keep working on a machine (or CI job) with no PostgreSQL.
"""

import asyncio
import uuid
from collections.abc import AsyncIterator
from datetime import datetime
from functools import lru_cache

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.core.config import get_settings

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """A time-ordered UUID primary key, generated by the database."""

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        server_default=text("uuidv7()"),
    )


class TimestampMixin:
    """UTC instants for when a row was created and last changed.

    ``updated_at`` is maintained with SQLAlchemy's ``onupdate``, which means
    updates made through the ORM bump it and a raw SQL ``UPDATE`` does not.
    That is the honest trade for now: a trigger would cover both, but it also
    hides the write from the ORM. Revisit if a service ever updates rows
    outside the ORM.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


@lru_cache
def get_engine() -> AsyncEngine:
    """The application engine, created once.

    Raises when ``DATABASE_URL`` is unset — deliberately at *use*, not at
    import: a process that only renders the OpenAPI schema (or a unit test
    that never touches the database) needs no configuration at all.
    """
    url = get_settings().database_url
    if not url:
        raise RuntimeError(
            "DATABASE_URL is not configured. Set it in backend/.env "
            "(postgresql+asyncpg://user:password@host:port/database).",
        )
    # pool_pre_ping: a pooled connection that the database has closed (a
    # restart, an idle timeout) is detected and replaced instead of surfacing
    # as a random failure on the next request.
    return create_async_engine(url, pool_pre_ping=True)


@lru_cache
def get_sessionmaker() -> async_sessionmaker[AsyncSession]:
    """Session factory. ``expire_on_commit=False`` keeps attributes readable
    after a commit, which is what response serialisation needs."""
    return async_sessionmaker(get_engine(), expire_on_commit=False)


async def dispose_engine() -> None:
    """Close the pool — called from the app's lifespan shutdown."""
    if get_engine.cache_info().currsize > 0:
        await get_engine().dispose()


async def get_session() -> AsyncIterator[AsyncSession]:
    """A session per request.

    The request-scoped transaction rule (first needed by F028's login): **the
    service that owns the work commits**; this dependency only guarantees the
    session is closed. A handler that raises commits nothing — the unit of
    work is discarded — which is the right default. The one deliberate
    exception lives in the login service: it commits its rate-limit counters
    *before* raising on a failed attempt, because a failed login that rolls
    back its own count would be a throttle that never throttles.
    """
    async with get_sessionmaker()() as session:
        yield session


READINESS_TIMEOUT_SECONDS = 5.0
"""How long the readiness probe waits for PostgreSQL before answering *down*.

A bound of the probe's own, not a deployment setting: readiness is asked over
and over by a monitor, and a probe that can hang is worse than one that answers
*no* — the whole point of F065 is that the question gets an answer.
"""


async def database_reachable(
    *,
    engine: AsyncEngine | None = None,
    timeout: float = READINESS_TIMEOUT_SECONDS,
) -> bool:
    """Whether PostgreSQL answers a trivial query — a fact, never a raise.

    ``SELECT 1`` rather than a read of some table: the question is whether the
    database is *reachable*, and a probe that read a table would answer *down*
    for a missing row, a rename or a permission — three situations where the
    application is fine. The statement goes through the pooled engine, so
    ``pool_pre_ping`` applies and a connection the server closed is replaced
    instead of reported.

    A boolean by the same argument as the converter's probe (F052) and the
    report engine's (F051): readiness is a boolean question, and a raising
    probe makes every caller write the same ``try/except``. The ``except``
    here is deliberately broad — a database that is not there fails as a
    refused connection, a timeout, a DNS error, or a ``DATABASE_URL`` that was
    never set — and every one of them means the same thing to the caller.
    ``engine`` is injectable the way ``convert_to_pdf``'s converter is, so a
    caller can ask the question of a database it chooses.
    """
    try:
        async with asyncio.timeout(timeout):
            async with (engine or get_engine()).connect() as connection:
                await connection.execute(text("SELECT 1"))
        return True
    except Exception:  # noqa: BLE001 — a probe answers a boolean, whatever raised
        return False
