"""Engine, sessions and the schema conventions every table follows.

F023 establishes three things that outlive the task, because changing them
later means rewriting migrations:

- **Explicit constraint names.** ``Base.metadata`` carries a naming convention,
  so an unnamed ``UniqueConstraint`` still reaches PostgreSQL as
  ``uq_<table>_<columns>``. Without one, constraint names are generated by the
  database, differ between environments, and every ``ALTER``/``DROP`` in a
  migration becomes guesswork.
- **UUID primary keys, version 7, generated by PostgreSQL.** ``uuidv7()`` is
  time-ordered, so new rows land at the end of the primary-key index instead of
  scattering through it the way v4 does — the same index locality as a
  sequence, without giving up an ID that is safe to expose. It requires
  PostgreSQL 18; this project pins 18.6 (ARCHITECTURE §8).
- **``timestamptz`` instants, never naive timestamps.** ``created_at`` and
  ``updated_at`` are UTC instants stored with a timezone; display-time
  conversion is a frontend concern (§14: "UTC instants for events").

The engine is created lazily. Importing this module must never require a
database — ``scripts/export_openapi.py`` imports the app to emit the schema,
and that has to keep working on a machine (or CI job) with no PostgreSQL.
"""

import uuid
from collections.abc import AsyncIterator
from datetime import datetime
from functools import lru_cache

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.core.config import get_settings

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """A time-ordered UUID primary key, generated by the database."""

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        server_default=text("uuidv7()"),
    )


class TimestampMixin:
    """UTC instants for when a row was created and last changed.

    ``updated_at`` is maintained with SQLAlchemy's ``onupdate``, which means
    updates made through the ORM bump it and a raw SQL ``UPDATE`` does not.
    That is the honest trade for now: a trigger would cover both, but it also
    hides the write from the ORM. Revisit if a service ever updates rows
    outside the ORM.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


@lru_cache
def get_engine() -> AsyncEngine:
    """The application engine, created once.

    Raises when ``DATABASE_URL`` is unset — deliberately at *use*, not at
    import: a process that only renders the OpenAPI schema (or a unit test
    that never touches the database) needs no configuration at all.
    """
    url = get_settings().database_url
    if not url:
        raise RuntimeError(
            "DATABASE_URL is not configured. Set it in backend/.env "
            "(postgresql+asyncpg://user:password@host:port/database).",
        )
    # pool_pre_ping: a pooled connection that the database has closed (a
    # restart, an idle timeout) is detected and replaced instead of surfacing
    # as a random failure on the next request.
    return create_async_engine(url, pool_pre_ping=True)


@lru_cache
def get_sessionmaker() -> async_sessionmaker[AsyncSession]:
    """Session factory. ``expire_on_commit=False`` keeps attributes readable
    after a commit, which is what response serialisation needs."""
    return async_sessionmaker(get_engine(), expire_on_commit=False)


async def dispose_engine() -> None:
    """Close the pool — called from the app's lifespan shutdown."""
    if get_engine.cache_info().currsize > 0:
        await get_engine().dispose()


async def get_session() -> AsyncIterator[AsyncSession]:
    """A session per request.

    Not wired to any endpoint yet: the request-scoped transaction rules arrive
    with the auth work (F028), which is where the first endpoint needs them.
    """
    async with get_sessionmaker()() as session:
        yield session
